### ISSUE TITLE
Problem when running

### ISSUE THREAD

**Issue by kingback1** [ChrisYang/RCPR#1]
hi, I'm traing to run your program on ubuntu, but after performing ./RCPR Model/fern.dat img.txt, i got into trouble.
"init done
opengl support available
here
Archive Exception during deserializing:
unsupported version
5
img/296814969_3.jpg
1
RCPR: RandomFerns.cpp:131: void RandomFerns::get_linepoint(cv::Mat, cv::Mat, std::vector<l1l2f1>, cv::Mat&): Assertion `line_pids.size()==num_fea_locs' failed."

i don't know what the version is supported.

Could you help me find solution?
Best regards.

**Comment by thuhuwei** [comment]
Hi, I have the same problem, did you solve it?

**Comment by ChrisYang** [comment]
This is the compatibility problem of the binary model. The original ferns in txt can be downloaded from:
https://www.cl.cam.ac.uk/~hy306/code/ferns.tar.gz
The run the serialisation code to make your binary model.

**Comment by thuhuwei** [comment]
Thanks, it works now. :+1:
